language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: VgZnMu1BOJdPSYV67uBnq3S20v+5iaNNZ65nsqQjLvwJV0Me1f3yF9CP9sHNyzmENrD9uPnabNE6Mx5P8XqW+vQ0OMIUSuAjpGtvNZTfHCkSqy87/nVqsSWutu4KR0qe5l6cICGAsVOOh8Mm7VeTMcIYnG5jsx2gH5b4aWfXM7aaSvN4VsNI8zOKqlwlDAVPBnOTHclE8Dsi7H6qm6vr1IzddOn+HMH9bP53Sj7pnXHVTXxW6DVvyAzt02NiTOh/nJhIbNNIpfqF3IAURR4bpAzkoAG+FgMtnwXkVx2kFYL3FkBRtlheztmgMQ5/7fLgIxPkpr4bUAhMlj8YGDFNItrRNFsqXZWRJ3xm+3mCxXNV1tehqkVGFYqqyUg1p76pvxVhcnDOlNV3ACHmceiDuxKJltqhOGFENPIPLZuFlSvPxy57ZHs5uKnG7M93UOK1BvmV4uaeuqHccN2KCtDkk6KRvk+jxqi+RGQLEfr5L7JbxjijlpiVDr81gXw+G7ao4iUFmUKwimXSXOwWG06XlcahZ/C8XcH7yJiszO33W6efiUADUhscY0swrKDShtG70B4dt72tygk9qXUB1TmBlH8yZYsZXdUVMEGKp1IvQ/D1CS8jhMNziJ+SESRXeVi2lg2Eom/HFgEujqTIwocPK4jg2xOvb1QVLGP/E6SVstw=
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    all_branches:  true
    tags:  true
    repo: xebialabs-community/xlr-samson-plugin
