language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: VgZnMu1BOJdPSYV67uBnq3S20v+5iaNNZ65nsqQjLvwJV0Me1f3yF9CP9sHNyzmENrD9uPnabNE6Mx5P8XqW+vQ0OMIUSuAjpGtvNZTfHCkSqy87/nVqsSWutu4KR0qe5l6cICGAsVOOh8Mm7VeTMcIYnG5jsx2gH5b4aWfXM7aaSvN4VsNI8zOKqlwlDAVPBnOTHclE8Dsi7H6qm6vr1IzddOn+HMH9bP53Sj7pnXHVTXxW6DVvyAzt02NiTOh/nJhIbNNIpfqF3IAURR4bpAzkoAG+FgMtnwXkVx2kFYL3FkBRtlheztmgMQ5/7fLgIxPkpr4bUAhMlj8YGDFNItrRNFsqXZWRJ3xm+3mCxXNV1tehqkVGFYqqyUg1p76pvxVhcnDOlNV3ACHmceiDuxKJltqhOGFENPIPLZuFlSvPxy57ZHs5uKnG7M93UOK1BvmV4uaeuqHccN2KCtDkk6KRvk+jxqi+RGQLEfr5L7JbxjijlpiVDr81gXw+G7ao4iUFmUKwimXSXOwWG06XlcahZ/C8XcH7yJiszO33W6efiUADUhscY0swrKDShtG70B4dt72tygk9qXUB1TmBlH8yZYsZXdUVMEGKp1IvQ/D1CS8jhMNziJ+SESRXeVi2lg2Eom/HFgEujqTIwocPK4jg2xOvb1QVLGP/E6SVstw=
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-samson-plugin
notifications:
  slack:
    secure: sryZzoljGmAF5FlbIVbslmr37yfur8woLyvZKpOHmDN5LWuUW+tX9xR033k99f0MWE4HYPKnRs8Nz7ni+YegBxLf+JKvFfJRLraHuuYEz4TWwBf8fcPa20wwM1K/itghVuwrvHxt2bWQMJbBa59JNhTOCZm7HUDU0pjuXs5bHSwLYF5Z5W8QZJPNuhmYuNjtockFZnSfHIky62uezWn3qMzrSWa84GR660zTQSCYSk+jJgM2LtrFbrXZHa96vI7/bxPoz69yJIWY7yZwePaoA1XCllDoFGVnaXzSHNjI2HdnpiA1wSBRQmcoRC3jhoqP1/YW0zcrD70/FUI6dSizPpvZV9Tub+Q/Xjq+N8nGoecUEvu/MSeot2/JJcBCGrV1Uaui2m8VvCyaoZt1Wp0htkEaydt4EiNpCUr9qJAM/0mewzoJ/uVubC8bjJUYzzIo2y142a1Jc4/OI5ZpF7DpoQl4d5XI83BVHVC1HsGRDcaHiRaEAEK2mxYZbQWlnCQE8ASb+NCa+BmcASst+dmpCVgE4zdyyiOYvVZTpTpCf4q7Pf2GD7VMoadvZKLryZS2hiUz9gZ//4oYq1xnxTu0MOgcTnC7YwyG4/E3RApb3I9c/R57ww+y+s79d7wo+Sgo9wA7vYwMNbHejoZdBbeM/8JGHMp9sH7MGrFMkbY3cS8=
